name = "EenAllesKanaal SMP Season 3"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c7a6b089c1815adc9dfc70165061eaf9f7d3310bcf3f1c7ee3ec4c74deb64be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

