name = "EenAllesKanaal SMP Season 3"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01e34511d561dbf13f34fca99683a8a0d8b6a4dae2b25fe8ff64d181e1a7f869"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
