name = "EenAllesKanaal SMP Season 3"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c43882299cc0cfc4130b98925ea69ab6ebfea05d532fd58e1daf6eef726ccd06"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

