[general]
	#Maximum compression level for blocks [1..9]
	# Default: 9
	# Range: 1 ~ 9
	maxCompressionLevel = 9

[blocks]
	enable_nether_star_block = true
	enable_refined_radiance_block = true
	enable_shadow_steel_block = true
	enable_andesite_alloy_block = true
	enable_asurine_block = true
	enable_brass_block = true
	enable_crimsite_block = true
	enable_experience_block = true
	enable_limestone_block = true
	enable_ochrum_block = true
	enable_scorchia_block = true
	enable_scoria_block = true
	enable_veridium_block = true
	enable_zinc_block = true
	enable_acacia_log_block = true
	enable_acacia_plank_block = true
	enable_amethyst_block = true
	enable_andesite_block = true
	enable_basalt_block = true
	enable_birch_log_block = true
	enable_birch_plank_block = true
	enable_blackstone_block = true
	enable_bone_block_block = true
	enable_clay_block = true
	enable_coal_block = true
	enable_cobbled_deepslate_block = true
	enable_cobblestone_block = true
	enable_copper_block = true
	enable_crimson_stem_block = true
	enable_crimson_plank_block = true
	enable_dark_oak_log_block = true
	enable_dark_oak_plank_block = true
	enable_deepslate_block = true
	enable_diamond_block = true
	enable_diorite_block = true
	enable_dirt_block = true
	enable_emerald_block = true
	enable_end_stone_block = true
	enable_glass_block = true
	enable_glowstone_block = true
	enable_gold_block = true
	enable_granite_block = true
	enable_grass_block = true
	enable_gravel_block = true
	enable_hay_block = true
	enable_honey_block = true
	enable_iron_block = true
	enable_jungle_log_block = true
	enable_jungle_plank_block = true
	enable_lapis_block = true
	enable_melon_block = true
	enable_netherite_block = true
	enable_netherrack_block = true
	enable_oak_log_block = true
	enable_oak_plank_block = true
	enable_obsidian_block = true
	enable_podzol_block = true
	enable_pumpkin_block = true
	enable_quartz_block = true
	enable_raw_copper_block = true
	enable_raw_iron_block = true
	enable_raw_gold_block = true
	enable_sand_block = true
	enable_sandstone_block = true
	enable_red_sand_block = true
	enable_redstone_block = true
	enable_snow_block = true
	enable_soul_sand_block = true
	enable_soul_soil_block = true
	enable_spruce_log_block = true
	enable_spruce_plank_block = true
	enable_stone_block = true
	enable_terracotta_block = true
	enable_tuff_block = true
	enable_warped_stem_block = true
	enable_warped_plank_block = true
