#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 27 08:01:00 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.6.zip
