name = "EenAllesKanaal SMP Season 3 Lite"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71241d4c11c9d2ae0dc1b45694a5994fdd736784eb367664b8f4d0b9d46beebc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

