name = "EenAllesKanaal SMP Season 3 Lite"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a43c1e4c502056b536ea1da3e95692020ef3ae8da200cba08d8125805b7e4d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

