name = "EenAllesKanaal SMP Season 3 Lite"
author = "EenAllesKanaal SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2528f0ffda6055fcf5ac8ecedf27bd5bc4164a48118a093294d0e1b3ef7fe7bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
